/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFPrincipal.java
 *
 * Created on 30/06/2011, 21:47:37
 */
package pizzaria.visao;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author FAETEC
 */
public class JFPrincipal extends javax.swing.JFrame {

    private JFCadPizza jfCadPizza = new JFCadPizza();
    private JFCadPedido jfCadpedido = new JFCadPedido();
    private JFCadBebida jfCadbebida = new JFCadBebida();
    private JFCadEstado jfCadEstado = new JFCadEstado();
    private JFCadCidade jfCadCidade = new JFCadCidade();
    private JFCadBairro jfCadBairro = new JFCadBairro();
    private JFCadFuncionario jfCadfuncionario = new JFCadFuncionario();
    private JFCadCliente jfCadCliente = new JFCadCliente();
    private JFCadTipoLog jfTPLogra = new JFCadTipoLog();
    private JFCadLog jfLogra = new JFCadLog();
    private JFCadLogin jfCadLogin = new JFCadLogin();
    private JDAltSenha jdAltSenha = new JDAltSenha(this, true);
    private JFCadEntregador jfCadEntregador = new JFCadEntregador();
    private JDCnsVenda jfCnsvenda = new JDCnsVenda(this, true);
    private JDSobre jdSobre = new JDSobre();

    /** Creates new form JFPrincipal */
    public JFPrincipal() {
        initComponents();
        lbUsuario.setText(JDEntra.getLogin().getAut_usuario());

        if (!JDEntra.getLogin().getAut_acesso().equals("1")) {
            jMenu1.setText("Consulta/Cadastro");
            itemEst.setText("Novo Estado...");
            itemCliente.setText("Novo Cliente...");
            itemTipLog.setText("Novo Tipo de Logradouro...");
            itemLog.setText("Novo Logradouro...");
            itemBairro.setText("Novo Bairro...");
            itemCid.setText("Nova Cidade...");
            itemEntregador.setText("Novo Entregador...");
            itemFuncionario.setText("Funcionário...");
            itemPizza.setText("Pizza...");
            itemBebida.setText("Bebida...");
            itemPedido.setText("Novo Pedido...");
            itemAltSenha.setText("Alterar Senha...");
            itemLogin.setEnabled(false);
            itemVenda.setEnabled(false);

        }
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {

            public void run() {
                jlHora.setText(new SimpleDateFormat("HH:mm:ss").format(new Date(System.currentTimeMillis())));
            }
        };
        timer.schedule(task, 1000, 1000);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlMens = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jlHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        itemEntregador = new javax.swing.JMenuItem();
        itemFuncionario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemBebida = new javax.swing.JMenuItem();
        itemPizza = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemLogin = new javax.swing.JMenuItem();
        itemAltSenha = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        itemTipLog = new javax.swing.JMenuItem();
        itemLog = new javax.swing.JMenuItem();
        itemBairro = new javax.swing.JMenuItem();
        itemCid = new javax.swing.JMenuItem();
        itemEst = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemPedido = new javax.swing.JMenuItem();
        itemVenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        itemCalc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        itemUsu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Pizzaria Tá Na Mesa");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHora.setText("jLabel2");

        jLabel1.setText("Usuário:");

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbUsuario.setForeground(new java.awt.Color(0, 153, 0));
        lbUsuario.setText("usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(lbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlMens, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jlMens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jlHora, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 12));

        jMenu1.setText("Cadastro");

        itemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        itemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/user1_16.png"))); // NOI18N
        itemCliente.setText("Clientes...");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(itemCliente);

        itemEntregador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/motboy.png"))); // NOI18N
        itemEntregador.setText("Entregador...");
        itemEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEntregadorActionPerformed(evt);
            }
        });
        jMenu1.add(itemEntregador);

        itemFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/funcionario_16.png"))); // NOI18N
        itemFuncionario.setText("Funcionário...");
        itemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemFuncionario);
        jMenu1.add(jSeparator2);

        itemBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/bebida.png"))); // NOI18N
        itemBebida.setText("Bebida...");
        itemBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBebidaActionPerformed(evt);
            }
        });
        jMenu1.add(itemBebida);

        itemPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/pizza.png"))); // NOI18N
        itemPizza.setText("Pizza...");
        itemPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPizzaActionPerformed(evt);
            }
        });
        jMenu1.add(itemPizza);
        jMenu1.add(jSeparator5);

        itemLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/login16x16.png"))); // NOI18N
        itemLogin.setText("Login...");
        itemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginActionPerformed(evt);
            }
        });
        jMenu1.add(itemLogin);

        itemAltSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/chave.gif"))); // NOI18N
        itemAltSenha.setText("Alterar Senha...");
        itemAltSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltSenhaActionPerformed(evt);
            }
        });
        jMenu1.add(itemAltSenha);
        jMenu1.add(jSeparator1);

        itemTipLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/tpLog_16x16.png"))); // NOI18N
        itemTipLog.setText("Tipos de Logradouro...");
        itemTipLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTipLogActionPerformed(evt);
            }
        });
        jMenu1.add(itemTipLog);

        itemLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/street-art.png"))); // NOI18N
        itemLog.setText("Logradouro...");
        itemLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogActionPerformed(evt);
            }
        });
        jMenu1.add(itemLog);

        itemBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/home.png"))); // NOI18N
        itemBairro.setText("Bairros...");
        itemBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBairroActionPerformed(evt);
            }
        });
        jMenu1.add(itemBairro);

        itemCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/cidade_16x16.png"))); // NOI18N
        itemCid.setText("Cidades...");
        itemCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCidActionPerformed(evt);
            }
        });
        jMenu1.add(itemCid);

        itemEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/cid_16x16.png"))); // NOI18N
        itemEst.setText("Estados...");
        itemEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEstActionPerformed(evt);
            }
        });
        jMenu1.add(itemEst);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        itemPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/novo_16.png"))); // NOI18N
        itemPedido.setText("Novo Pedido...");
        itemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(itemPedido);

        itemVenda.setText("Venda");
        itemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVendaActionPerformed(evt);
            }
        });
        jMenu2.add(itemVenda);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ferramenta");

        itemCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/calc_16x16.png"))); // NOI18N
        itemCalc.setText("Calculadora...");
        itemCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalcActionPerformed(evt);
            }
        });
        jMenu4.add(itemCalc);
        jMenu4.add(jSeparator3);
        jMenu4.add(jSeparator4);

        itemUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/usuario2_16.png"))); // NOI18N
        itemUsu.setText("Usuários...");
        jMenu4.add(itemUsu);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Ajuda");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria/icons/copyright16x16.png"))); // NOI18N
        jMenuItem1.setText("Sobre...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        jfCadCliente = new JFCadCliente();
        jfCadCliente.setVisible(true);
}//GEN-LAST:event_itemClienteActionPerformed

    private void itemTipLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTipLogActionPerformed
        jfTPLogra = new JFCadTipoLog();
        jfTPLogra.setVisible(true);
}//GEN-LAST:event_itemTipLogActionPerformed

    private void itemLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogActionPerformed
        jfLogra = new JFCadLog();
        jfLogra.setVisible(true);
}//GEN-LAST:event_itemLogActionPerformed

    private void itemBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBairroActionPerformed
        jfCadBairro = new JFCadBairro();
        jfCadBairro.setVisible(true);
}//GEN-LAST:event_itemBairroActionPerformed

    private void itemCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCidActionPerformed
        jfCadCidade = new JFCadCidade();
        jfCadCidade.setVisible(true);
}//GEN-LAST:event_itemCidActionPerformed

    private void itemEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEstActionPerformed
        if (JDEntra.getLogin().getAut_acesso().equals("1")) {
            jfCadEstado = new JFCadEstado();
            jfCadEstado.setVisible(true);
        } else {
            new JDCnsEstado(this, true).setVisible(true);
        }
}//GEN-LAST:event_itemEstActionPerformed

    private void itemCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalcActionPerformed
        try {
            Runtime.getRuntime().exec("calc.exe");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_itemCalcActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Deseja Finalizar o Sistema?", "Confirme", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void itemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginActionPerformed
        if (JDEntra.getLogin().getAut_acesso().equals("1")) {
            jfCadLogin = new JFCadLogin();
            jfCadLogin.setVisible(true);
        } else {
            //jfCadLogin.setVisible(false);
            JOptionPane.showMessageDialog(null, "Usuario " + JDEntra.getLogin().getAut_usuario().trim() + " não tem permissão para essa tela !");
        }
    }//GEN-LAST:event_itemLoginActionPerformed

private void itemEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntregadorActionPerformed
    if (JDEntra.getLogin().getAut_acesso().equals("1")) {
        jfCadEntregador = new JFCadEntregador();
        jfCadEntregador.setVisible(true);
    } else {
        new JDCnsEntregador(this, true).setVisible(true);
    }

}//GEN-LAST:event_itemEntregadorActionPerformed
private void itemBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBebidaActionPerformed
    if (JDEntra.getLogin().getAut_acesso().equals("1")) {
        jfCadbebida = new JFCadBebida();
        jfCadbebida.setVisible(true);
    } else {
        new JDCnsBebida(this, true).setVisible(true);
    }
}//GEN-LAST:event_itemBebidaActionPerformed

private void itemPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPizzaActionPerformed
    if (JDEntra.getLogin().getAut_acesso().equals("1")) {
        jfCadPizza = new JFCadPizza();
        jfCadPizza.setVisible(true);
    } else {
        new JDCnsPizza(this, true).setVisible(true);
    }
}//GEN-LAST:event_itemPizzaActionPerformed

private void itemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPedidoActionPerformed
    jfCadpedido = new JFCadPedido();
    jfCadpedido.setVisible(true);
}//GEN-LAST:event_itemPedidoActionPerformed

private void itemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFuncionarioActionPerformed
    if (JDEntra.getLogin().getAut_acesso().equals("1")) {
        jfCadfuncionario = new JFCadFuncionario();
        jfCadfuncionario.setVisible(true);
    } else {
        new JDCnsFuncionario(this, true).setVisible(true);
    }
}//GEN-LAST:event_itemFuncionarioActionPerformed

private void itemAltSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltSenhaActionPerformed
    jdAltSenha = new JDAltSenha(this, true);
    jdAltSenha.setVisible(true);
}//GEN-LAST:event_itemAltSenhaActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    jdSobre = new JDSobre();
    jdSobre.setVisible(true);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void itemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVendaActionPerformed
    if (JDEntra.getLogin().getAut_acesso().equals("1")) {
        jfCnsvenda = new JDCnsVenda(this, true);
        jfCnsvenda.setVisible(true);
    } else {
        jfCnsvenda.setVisible(false);
    }
}//GEN-LAST:event_itemVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAltSenha;
    private javax.swing.JMenuItem itemBairro;
    private javax.swing.JMenuItem itemBebida;
    private javax.swing.JMenuItem itemCalc;
    private javax.swing.JMenuItem itemCid;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemEntregador;
    private javax.swing.JMenuItem itemEst;
    private javax.swing.JMenuItem itemFuncionario;
    private javax.swing.JMenuItem itemLog;
    private javax.swing.JMenuItem itemLogin;
    private javax.swing.JMenuItem itemPedido;
    private javax.swing.JMenuItem itemPizza;
    private javax.swing.JMenuItem itemTipLog;
    private javax.swing.JMenuItem itemUsu;
    private javax.swing.JMenuItem itemVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlMens;
    private javax.swing.JLabel lbUsuario;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLbUsuario() {
        return lbUsuario;
    }

    public void setLbUsuario(javax.swing.JLabel lbUsuario) {
        this.lbUsuario = lbUsuario;
    }
}
